### ISSUE TITLE
Direct wss connection to the hub

### ISSUE THREAD

**Issue by VibroAxe** [washcroft/LightwaveRF-LinkPlus#1]
Given we still have no official API from lightwave did you get anywhere with direct connection?

I don't have a gen 2 hub to play with but wondered what happened if you just wss direct to the hub or if we need to get more in-depth with wireshark

**Comment by washcroft** [comment]
I've done very little on this, but it doesn't appear the hub is listening with any services at present (other than HomeKit), so likely no local API exists at all in there.

Currently, it will establish an outbound WebSocket connection to the cloud API, since that's where all the command and control is orchestrated (mobile/web apps are just connecting to the same cloud API).

If the cloud service is down, nothing will work (except the physical switches obviously).

**Comment by VibroAxe** [comment]
I'm deeply disappointed in lightwave on this one, but it seems to be a growing and concerning trend in the smartphone market ATM.

Thanks for your work
